// app
export const SET_THEME = "SET_THEME";

// story
export const FETCH_STORIES_IDS = "FETCH_STORIES_IDS";

export const FETCH_STORIES_REQUEST = "FETCH_STORIES_REQUEST";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const FETCH_STORIES_FAILURE = "FETCH_STORIES_FAILURE";
