// app
export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_LAYOUT = "TOGGLE_LAYOUT";

// story
export const FETCH_IDS_REQUEST = "FETCH_STORIES_IDS_REQUEST";
export const FETCH_IDS_SUCCESS = "FETCH_STORIES_IDS_SUCCESS";
export const FETCH_IDS_FAILURE = "FETCH_STORIES_IDS_FAILURE";

export const FETCH_STORIES_REQUEST = "FETCH_STORIES_REQUEST";
export const FETCH_STORIES_SUCCESS = "FETCH_STORIES_SUCCESS";
export const FETCH_STORIES_FAILURE = "FETCH_STORIES_FAILURE";
